import type { Artwork } from '@/types'

const IMG = 'https://raw.githubusercontent.com/Anon2026-hyped/Boanerges/main'

// Seed catalog. In Phase 3 this moves to Supabase; the shape stays identical
// (integer minor units: USD cents), so consumers won't change.
export const artworks: Artwork[] = [
  {
    id: 'herald',
    slug: 'chaos-in-eko',
    title: 'Chaos in Eko',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 200000,
    imageUrl: `${IMG}/Hero(1).jpg`,
  },
  {
    id: 'lion',
    slug: 'nwunye-odogwu',
    title: 'Nwunye Odogwu',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 100000,
    imageUrl: `${IMG}/IMG_1089(1).jpg`,
  },
  {
    id: 'crown',
    slug: 'panic',
    title: 'Panic',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 40000,
    imageUrl: `${IMG}/IMG_1093(1).jpg`,
  },
  {
    id: 'altar',
    slug: 'african-cowboy',
    title: 'African Cowboy',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 50000,
    imageUrl: `${IMG}/IMG_1094(1).jpg`,
  },
  {
    id: 'flame',
    slug: 'the-watcher',
    title: 'The Watcher',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 100000,
    imageUrl: `${IMG}/IMG_1095(1).jpg`,
  },
  {
    id: 'veil',
    slug: 'the-guardian',
    title: 'The Guardian',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 100000,
    imageUrl: `${IMG}/IMG_1097(1).jpg`,
  },
  {
    id: 'oath',
    slug: 'die-lit',
    title: 'Die Lit',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 50000,
    imageUrl: `${IMG}/IMG_1098(1).jpg`,
  },
  {
    id: 'psalm',
    slug: 'odogwu-in-repose',
    title: 'Odogwu in Repose',
    medium: 'Acrylic on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 50000,
    imageUrl: `${IMG}/IMG_1100(1).jpg`,
  },
  {
    id: 'relic',
    slug: 'ampute-samurai',
    title: 'Ampute Samurai',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 50000,
    imageUrl: `${IMG}/IMG_1099(1).jpg`,
  },
  {
    id: 'covenant',
    slug: 'end-of-days',
    title: 'End of Days',
    medium: 'Oil on Canvas',
    edition: 'EDITION OF 111 · BLIND DROP',
    priceUsdCents: 80000,
    imageUrl: `${IMG}/IMG_1101(1).jpg`,
  },
]
